site_name: Python
site_author: "Vu Anh"
google_analytics: ['UA-68978617-1', 'magizbox.com']
repo_url: https://github.com/magizbox/python/
edit_uri: edit/master/docs/

pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "<span class='fa fa-cloud-download'></span> Get Started": 'get_started.md'
- "<span class='fa fa-book'></span> Learn":
  - "Basic Syntax":
    - "Overview": 'basic_syntax.md'
    - "Yield and Generator": 'basic_syntax_yield.md'
  - "Data Structure":
    - "Number": 'data_number.md'
    - "String": 'data_string.md'
    - "Object": 'data_object.md'
    - "Collection": 'data_collection.md'
    - "Time": 'data_time.md'
  - "OOP": 'oop.md'
  - "Operating System": 'os.md'
  - "IO": 'io.md'
  - "Networking": 'networking.md'
  - "Concurrency and Parallelism": 'concurrency_parallelism.md'
  - "Event Based": 'event_based.md'
  - "Logging": 'logging.md'
  - "Configuration": 'configuration.md'
  - "Test": 'test.md'
  - "Web": 'web.md'
  - "IDE": 'ide.md'
  - "Package Manager": 'package_manager.md'
  - "Environment": 'environment.md'
  - "Module": 'make_a_module.md'
  - "Production": 'production.md'
- "<span class='fa fa-question-circle'></span> Ask": "ask.md"

markdown_extensions:
    - footnotes

extra_css:
  - css/book.css
  - css/course.css
  - css/video.css
  - css/custom.css
extra_javascript:
  - js/underscore.js
  - js/jquery.js
  - js/gspreadsheet.js
  - js/book.js
  - js/course.js
  - js/video.js
  - js/script.js
