site_name: Python
site_author: "Vu Anh"
google_analytics: ['UA-68978617-1', 'magizbox.com']
repo_url: https://github.com/magizbox/python/
edit_uri: edit/master/docs/

pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "<span class='fa fa-cloud-download'></span> Get Started": 'get_started.md'
- "<span class='fa fa-book'></span> Tutorials":
  - "Introduction": 'tutorials.md'
  - "Basic Syntax":
    - "Overview": 'basic_syntax.md'
    - "Yield and Generator": 'basic_syntax_yield.md'
  - "Data Structure":
    - "Number": 'datastructure_number.md'
    - "Collection (List, Set, Turple)": 'datastructure_collection.md'
    - "String": 'datastructure_string.md'
    - "Time": 'datastructure_time.md'
    - "Object": 'datastructure_object.md'
  - "Python IO": 'io.md'
  - "Object Oriented Programming":
    - "Classes and Objects": 'oop.md'
    - "Design Patterns": 'design_patterns.md'
  - "Operating System": 'os.md'
  - "Networking": 'networking.md'
  - "Concurrency and Parallelism": 'concurrency_parallelism.md'
  - "Event Based": 'event_based.md'
  - "Web Development": 'web.md'
- "<span class='fa fa-cube'></span> Software Development":
  - "Logging": 'logging.md'
  - "Configuration": 'configuration.md'
  - "Command Line": 'command_line.md'
  - "Test": 'test.md'
  - "IDE": 'ide.md'
  - "Package Manager": 'package_manager.md'
  - "Environment": 'environment.md'
  - "Module": 'make_a_module.md'
  - "Production": 'production.md'

markdown_extensions:
    - footnotes

extra_css:
  - components/magiz-c-book/src/book.css
  - components/magiz-c-course/src/course.css
  - components/magiz-c-video/src/video.css
  - components/magiz-c-benchmark/src/benchmark.css
  - components/magiz-c-paper/src/paper.css
  - components/magiz-doc/style.css
  - css/custom.css

extra_javascript:
  - components/underscore/underscore.js
  - components/magiz-c-book/src/gspreadsheet.js
  - components/magiz-c-paper/src/paper.js
  - components/magiz-c-course/src/course.js
  - components/magiz-c-benchmark/src/benchmark.js
  - components/magiz-c-benchmark/src/bootstrap-popup.js
  - components/magiz-c-book/src/book.js
  - components/magiz-c-video/src/video.js
  - components/jquery/dist/jquery.js
  - components/magiz-doc/doc.js
  - components/magiz-doc/footer.js
